[binaries]
; c = '/mnt/part2/owned/llvm-mingw-20250430-msvcrt-ubuntu-22.04-x86_64/bin/clang'
cpp = '/mnt/part2/owned/llvm-mingw-20250430-msvcrt-ubuntu-22.04-x86_64/bin/clang++'
ar = '/mnt/part2/owned/llvm-mingw-20250430-msvcrt-ubuntu-22.04-x86_64/bin/llvm-ar'
cpp_ld = '/mnt/part2/owned/llvm-mingw-20250430-msvcrt-ubuntu-22.04-x86_64/bin/ld.lld'
cmake = 'cmake'

[host_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[target_machine]
system = 'windows'
cpu_family = 'x86'
cpu = 'i686'
endian = 'little'

[built-in options]
; c_args = ['-target=i686-w64-mingw32', '-fms-extensions', '-Iinclude']
cpp_args = ['--target=i686-w64-mingw32', '-fms-extensions']
; c_link_args = ['-target=i686-w64-mingw32']
cpp_link_args = ['--target=i686-w64-mingw32', '-static', '-shared']

[properties]
is_clang_mingw = 'true'
