import pefile

dll_name = "d2d1"
dll_path = f"/home/louisbui63/.wine/drive_c/windows/syswow64/{dll_name}.dll"
pe = pefile.PE(dll_path)


if hasattr(pe, "DIRECTORY_ENTRY_EXPORT"):
    print("/////////////////////////////proxy.cpp/////////////////////////////////")
    print("// autogenerated file, do not edit")
    print('#include "proxy.hpp"')
    # for exp in pe.DIRECTORY_ENTRY_EXPORT.symbols:
    #     if exp.name:
    #         print(
    #             f'#pragma comment(linker, "/export:{exp.name.decode()}=hooked__{exp.name.decode()}")'
    #         )

    print(
        """
void Proxy::Init(HMODULE hProxy) {
ProxyModuleHandle = hProxy;

wchar_t realDllPath[MAX_PATH];
GetSystemDirectoryW(realDllPath, MAX_PATH);
    """
    )
    print(f'wcscat_s(realDllPath, L"\\\\{dll_name}.dll");')
    print("""
OriginalModuleHandle = LoadLibraryW(realDllPath);
if (OriginalModuleHandle == nullptr) {
    """)
    print(
        f'    MessageBoxW(nullptr, L"Cannot load original {dll_name}.dll library", L"Proxy",'
    )
    print("""
            MB_ICONERROR);
    ExitProcess(0);
}

#define RESOLVE(fn) real__##fn = (void*)GetProcAddress(OriginalModuleHandle, #fn)
    """)
    for exp in pe.DIRECTORY_ENTRY_EXPORT.symbols:
        if exp.name:
            print(f"RESOLVE({exp.name.decode()});")
    print("""
#undef RESOLVE
}
    """)
    for exp in pe.DIRECTORY_ENTRY_EXPORT.symbols:
        if exp.name:
            print(f"__attribute__((naked)) void hooked__{exp.name.decode()}() {{")
            print(f'  __asm__("jmp _real__{exp.name.decode()};":);')
            print("}")

    print("/////////////////////////////proxy.hpp/////////////////////////////////")
    print("// autogenerated file, do not edit")
    print("""
#pragma once
#include <windows.h>

class Proxy {
public:
  static void Init(HMODULE hProxy);

  static inline HMODULE ProxyModuleHandle{};
  static inline HMODULE OriginalModuleHandle{};
};
  """)
    for exp in pe.DIRECTORY_ENTRY_EXPORT.symbols:
        if exp.name:
            print(f"static inline void *real__{exp.name.decode()}{{}};")
    print("/////////////////////////////d2d1.def/////////////////////////////////")
    print(f"LIBRARY {dll_name}")
    print("EXPORTS")
    for exp in pe.DIRECTORY_ENTRY_EXPORT.symbols:
        if exp.name:
            print(f"  {exp.name.decode()}=hooked__{exp.name.decode()} @{exp.ordinal}")
